name: ClearFlight-CI/CD

on: 
  push:
    branches:
      - main 

jobs:
  run-tests:
    name: Clearflight-Checks
    runs-on: ubuntu-latest
    env:
      AVIATIONSTACK_API_KEY: ${{ secrets.AVIATIONSTACK_API_KEY }}
      WEATHERSTACK_API_KEY: ${{ secrets.WEATHERSTACK_API_KEY }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Requirements
      run: make requirements

    - name: Dev setup
      run: make dev-setup

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Run checks
      run: make run-checks

  docker-build:
    name: Clearflight-Docker-Build
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/clearflightapi:latest
